/********************************************************************
* GEFICA.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error GEFICA.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableGEFICA();
extern void G__cpp_setup_inheritanceGEFICA();
extern void G__cpp_setup_typetableGEFICA();
extern void G__cpp_setup_memvarGEFICA();
extern void G__cpp_setup_globalGEFICA();
extern void G__cpp_setup_memfuncGEFICA();
extern void G__cpp_setup_funcGEFICA();
extern void G__set_cpp_environmentGEFICA();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TrueCoaxial.h"
#include "Field.h"
#include "Detector.h"
#include "Planar.h"
#include "Planar1D.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GEFICALN_TClass;
extern G__linked_taginfo G__GEFICALN_TBuffer;
extern G__linked_taginfo G__GEFICALN_TMemberInspector;
extern G__linked_taginfo G__GEFICALN_TObject;
extern G__linked_taginfo G__GEFICALN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GEFICALN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GEFICALN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__GEFICALN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GEFICALN_TF1;
extern G__linked_taginfo G__GEFICALN_GEFICA;
extern G__linked_taginfo G__GEFICALN_GEFICAcLcLDetector;
extern G__linked_taginfo G__GEFICALN_GEFICAcLcLField;
extern G__linked_taginfo G__GEFICALN_GEFICAcLcLTrueCoaxial;
extern G__linked_taginfo G__GEFICALN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__GEFICALN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__GEFICALN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__GEFICALN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__GEFICALN_TVectorTlEfloatgR;
extern G__linked_taginfo G__GEFICALN_TVectorTlEdoublegR;
extern G__linked_taginfo G__GEFICALN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__GEFICALN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__GEFICALN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__GEFICALN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__GEFICALN_TMatrixTSymlEdoublegR;
extern G__linked_taginfo G__GEFICALN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__GEFICALN_TMatrixTSparselEdoublegR;
extern G__linked_taginfo G__GEFICALN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__GEFICALN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__GEFICALN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__GEFICALN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__GEFICALN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__GEFICALN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__GEFICALN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__GEFICALN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__GEFICALN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__GEFICALN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__GEFICALN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__GEFICALN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__GEFICALN_GEFICAcLcLPlanar1D;

/* STUB derived class for protected member access */
